version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s: %(message)s'
  advanced:
    format: '%(asctime)s %(threadName)-10s %(name)-20s %(levelname)-7s: %(message)s'
    datefmt: '%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    delay: true
    maxBytes: 800000
    backupCount: 2
    encoding: "utf-8"
    formatter: advanced
loggers:
  artisanlib:
    level: INFO
    handlers: [file]
    propagate: no
  plus:
    level: INFO
    handlers: [file]
    propagate: no
  pymodbus.logging:
    level: ERROR
    handlers: [file]
    propagate: no
root:
  level: ERROR
  handlers: [file]
